package credentials;

public class Assignment {
	// DO NOT EDIT THIS FILE!
	// CODE:  Course (NNN), Type (0=studio, 1=lab, etc.), Which one (00-99)
	public static final int ASSIGNMENT_ID = 247000;
	public static final boolean OPEN = true;
	public static final boolean POST_TO_BRIDGES = true;
}
